# ============================================================
# AUTONOMOUS AI SOFTWARE ENGINEER
# PHASE 3 - CODING AGENT
# ============================================================

import os
from architect_agent import create_plan, create_architecture


def create_project_structure(project_name, architecture):

    print("\n💻 Coding Agent is creating the project...\n")

    # Create the main generated-project directory
    project_path = os.path.join(
        "generated_projects",
        project_name
    )

    os.makedirs(project_path, exist_ok=True)

    # Create directories
    directories = [
        "app",
        "app/api",
        "app/services",
        "app/models",
        "app/database",
        "app/security",
        "tests"
    ]

    for directory in directories:
        os.makedirs(
            os.path.join(project_path, directory),
            exist_ok=True
        )

    # --------------------------------------------------------
    # Create main.py
    # --------------------------------------------------------

    main_code = '''"""
Main application entry point.
"""

def main():
    print("Application started successfully.")


if __name__ == "__main__":
    main()
'''

    create_file(
        project_path,
        "app/main.py",
        main_code
    )

    # --------------------------------------------------------
    # Create requirements.txt
    # --------------------------------------------------------

    requirements = """fastapi
uvicorn
pytest
python-dotenv
"""

    create_file(
        project_path,
        "requirements.txt",
        requirements
    )

    # --------------------------------------------------------
    # Create README.md
    # --------------------------------------------------------

    readme = f"""# {project_name}

This project was generated by the
Autonomous AI Software Engineering Platform.

## Architecture

{architecture["architecture_style"]}

## Modules

"""

    for module in architecture["modules"]:
        readme += f"- {module}\n"

    readme += """
## Testing

Automated tests will be added by the Testing Agent.

## Security

Security analysis will be performed by the Security Agent.
"""

    create_file(
        project_path,
        "README.md",
        readme
    )

    # --------------------------------------------------------
    # Create initial test
    # --------------------------------------------------------

    test_code = '''def test_basic_system():
    assert True
'''

    create_file(
        project_path,
        "tests/test_basic.py",
        test_code
    )

    return project_path


def create_file(project_path, relative_path, content):

    file_path = os.path.join(
        project_path,
        relative_path
    )

    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(content)

    print(f"  📄 Created: {relative_path}")


# ============================================================
# MAIN PROGRAM
# ============================================================

if __name__ == "__main__":

    print("=" * 70)
    print("🤖 AUTONOMOUS AI SOFTWARE ENGINEER")
    print("=" * 70)

    requirement = input(
        "\nWhat software do you want to build?\n> "
    )

    # Planner
    plan = create_plan(requirement)

    # Architect
    architecture = create_architecture(plan)

    # Convert requirement into a safe folder name
    project_name = (
        requirement
        .replace(" ", "_")
        .replace("/", "_")
        .replace("\\", "_")
        .replace(":", "")
        .replace("?", "")
    )

    project_path = create_project_structure(
        project_name,
        architecture
    )

    print("\n" + "=" * 70)
    print("📦 PROJECT CREATED")
    print("=" * 70)

    print(f"\nProject location:")
    print(project_path)

    print("\n✅ Coding Agent finished.")